version: "3"
services:
  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx-password
      - DOCKER_INFLUXDB_INIT_ORG=sch8fa
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=influx-auth-token
    volumes:
      - influxdb:/var/lib/influxdb2

  gasmeter:
    build: .
    privileged: true
    depends_on:
      - influxdb
    # restart: always

volumes:
  influxdb: